// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7oI5CL6W30lLg_vyzHa4juJdChDft6Q',
    appId: '1:340670701164:web:ff85f4e3b84a8df18fc249',
    messagingSenderId: '340670701164',
    projectId: 'aulamatheus-304ae',
    authDomain: 'aulamatheus-304ae.firebaseapp.com',
    storageBucket: 'aulamatheus-304ae.appspot.com',
    measurementId: 'G-6YSZ362TYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNB3FHDe0aW_HXJ67QOdMYHuJ17PpNr7k',
    appId: '1:340670701164:android:fafe4c915128cdd68fc249',
    messagingSenderId: '340670701164',
    projectId: 'aulamatheus-304ae',
    storageBucket: 'aulamatheus-304ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0UtFE8ucBpX34WUcaVOyngyhDVyik0A',
    appId: '1:340670701164:ios:ee8e49fa9b2200348fc249',
    messagingSenderId: '340670701164',
    projectId: 'aulamatheus-304ae',
    storageBucket: 'aulamatheus-304ae.appspot.com',
    iosClientId: '340670701164-ca05qth5u2apru93qktgdmeioahen1gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe0UtFE8ucBpX34WUcaVOyngyhDVyik0A',
    appId: '1:340670701164:ios:8360807a115e2f618fc249',
    messagingSenderId: '340670701164',
    projectId: 'aulamatheus-304ae',
    storageBucket: 'aulamatheus-304ae.appspot.com',
    iosClientId: '340670701164-r17jrkk3e8drhq08j695162pglv1g42c.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaflutter.RunnerTests',
  );


}
